# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2dcb18ee314e33494b819d799422518b"
name = "Assistente de Apoio ao Cliente"
application_url = "https://tripat3s.com"
embedded = false

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
